// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Auxiliary: typeof import('./examples/color/auxiliary.vue')['default']
    CategoriesTable: typeof import('./theme/components/demo/CategoriesTable.vue')['default']
    DemoBlock: typeof import('./theme/components/demo/DemoBlock.vue')['default']
    DemoContainer: typeof import('./theme/components/demo/DemoContainer.vue')['default']
    OptionalValue: typeof import('./theme/components/demo/OptionalValue.vue')['default']
    PropsTable: typeof import('./theme/components/demo/PropsTable.vue')['default']
  }
}

export { }
