// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AgmButton: typeof import('augma')['AgmButton']
    AgmIcon: typeof import('augma')['AgmIcon']
    Auxiliary: typeof import('./examples/color/auxiliary.vue')['default']
    CategoriesTable: typeof import('./theme/components/demo/CategoriesTable.vue')['default']
    DarkModeSwitch: typeof import('./theme/components/DarkModeSwitch.vue')['default']
    DemoBlock: typeof import('./theme/components/demo/DemoBlock.vue')['default']
    DemoContainer: typeof import('./theme/components/demo/DemoContainer.vue')['default']
    Home: typeof import('./theme/components/Home.vue')['default']
    HomeHero: typeof import('./theme/components/HomeHero.vue')['default']
    IRiDragMove: typeof import('~icons/ri/drag-move')['default']
    IRiDragMoveLine: typeof import('~icons/ri/drag-move-line')['default']
    IRiGithubLine: typeof import('~icons/ri/github-line')['default']
    IRiMoonLine: typeof import('~icons/ri/moon-line')['default']
    IRiSunLine: typeof import('~icons/ri/sun-line')['default']
    IRiTwitterLine: typeof import('~icons/ri/twitter-line')['default']
    Layout: typeof import('./theme/Layout.vue')['default']
    Navbar: typeof import('./theme/components/Navbar.vue')['default']
    NavLinks: typeof import('./theme/components/NavLinks.vue')['default']
    OptionalValue: typeof import('./theme/components/demo/OptionalValue.vue')['default']
    PropsTable: typeof import('./theme/components/demo/PropsTable.vue')['default']
  }
}

export { }
