/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AgmIcon: typeof import('augma')['AgmIcon']
    Auxiliary: typeof import('./examples/color/auxiliary.vue')['default']
    CategoriesTable: typeof import('./theme/components/demo/CategoriesTable.vue')['default']
    DemoBlock: typeof import('./theme/components/demo/DemoBlock.vue')['default']
    DemoContainer: typeof import('./theme/components/demo/DemoContainer.vue')['default']
    OptionalValue: typeof import('./theme/components/demo/OptionalValue.vue')['default']
    PropsTable: typeof import('./theme/components/demo/PropsTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
