import type { Page } from '@playwright/test'
import { expect, test } from '@playwright/test'

async function openSystemApp(page: Page, name: string) {
  await page.getByRole('button', { name: '系统菜单', exact: true }).click()
  await page.getByRole('button', { name, exact: true }).click()
}

test('original empty view, weather toggle and keyboard close', async ({ page }) => {
  await page.setViewportSize({ width: 724, height: 656 })
  await page.goto('/ar/')
  await expect(page.locator('.ar-app')).toHaveCSS('background-color', 'rgb(117, 117, 117)')
  await expect(page.locator('.device-window')).toHaveCount(0)
  await expect(page.locator('.world-scene')).toHaveCount(0)
  await expect(page.locator('.dock-buttons > .orb-button')).toHaveCount(9)
  await expect(page.locator('.system-clock time')).toHaveCSS('color', 'rgb(255, 255, 255)')
  const weather = page.getByRole('button', { name: '天气', exact: true })
  await weather.click()
  await expect(page.locator('.weather-temperature')).toHaveText('-3°C')
  await page.getByLabel('天气示例城市').selectOption('上海')
  await expect(page.locator('.weather-temperature')).toHaveText('18°C')
  await page.keyboard.press('Escape')
  await expect(page.locator('.device-window')).toHaveCount(0)
  await expect(weather).toBeFocused()
  await weather.click()
  await weather.click()
  await expect(page.locator('.device-window')).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollHeight <= innerHeight)).toBe(true)
})

test('scan, select an anchor, navigate and read device notifications', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/ar/')
  await page.getByRole('button', { name: '空间', exact: true }).click()
  await page.getByRole('button', { name: '扫描空间', exact: true }).click()
  await expect(page.getByText('已识别 3 个空间锚点')).toBeVisible()
  await page.getByRole('button', { name: '固定空间锚点', exact: true }).click()
  await expect(page.getByRole('button', { name: '释放空间锚点' })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: '选择中央绿洲', exact: true }).click()
  await expect(page.locator('.selected-place h3')).toContainText('中央绿洲')
  await page.getByRole('button', { name: '导航到这里' }).click()
  await expect(page.locator('.spatial-map')).toBeVisible()
  for (let i = 0; i < 4; i++)
    await page.getByRole('button', { name: '前进一步' }).click()
  await expect(page.getByRole('progressbar', { name: '路线进度' })).toHaveAttribute('aria-valuenow', '100')
  await expect(page.locator('.route-instruction')).toContainText('已到达中央绿洲')
  await openSystemApp(page, '通知')
  await expect(page.getByRole('heading', { name: '已到达目的地', exact: true })).toBeVisible()
  await expect(page.locator('.notification-count')).toHaveCount(0)
  await page.getByRole('button', { name: '清空通知' }).click()
  await expect(page.getByRole('heading', { name: '通知已清空' })).toBeVisible()
  expect(errors).toEqual([])
})

test('sleep cancels a scan and waking restores device controls', async ({ page }) => {
  await page.goto('/ar/')
  await page.getByRole('button', { name: '空间', exact: true }).click()
  await page.getByRole('button', { name: '扫描空间', exact: true }).click()
  await openSystemApp(page, '设备')
  await page.getByRole('button', { name: '待机', exact: true }).click()
  await page.getByRole('button', { name: '摄像头', exact: true }).click()
  await expect(page.getByRole('button', { name: '开启摄像头' })).toBeDisabled()
  await page.getByRole('button', { name: '空间', exact: true }).click()
  await expect(page.getByRole('button', { name: '扫描空间', exact: true })).toBeDisabled()
  await expect(page.getByRole('progressbar', { name: '空间扫描' })).toHaveAttribute('aria-valuenow', '0')
  await page.getByRole('button', { name: '唤醒设备' }).click()
  await expect(page.getByRole('button', { name: '扫描空间', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: '城市漫游', exact: true }).click()
  await expect(page.getByRole('button', { name: '选择光之美术馆' })).toBeVisible()
  await openSystemApp(page, '设备')
  await page.getByRole('button', { name: '断开', exact: true }).click()
  await page.getByRole('button', { name: '空间', exact: true }).click()
  await expect(page.getByRole('button', { name: '选择光之美术馆' })).toHaveCount(0)
})

test('display settings persist and reset with keyboard focus restored', async ({ page }) => {
  await page.goto('/ar/')
  await openSystemApp(page, '设置')
  await page.getByRole('switch', { name: '深色视界' }).click()
  await page.getByRole('switch', { name: '专注模式' }).click()
  const opacity = page.getByRole('slider', { name: '面板不透明度' })
  await opacity.focus()
  await page.keyboard.press('Home')
  await expect(opacity).toHaveAttribute('aria-valuenow', '60')
  await expect(page.locator('.world-marker')).toHaveCount(0)
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-agm-theme', 'dark')
  await openSystemApp(page, '设置')
  await expect(page.getByRole('switch', { name: '专注模式' })).toBeChecked()
  await page.getByRole('button', { name: '恢复默认设置', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '恢复默认设置' })
  await expect(dialog).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: '恢复默认设置', exact: true })).toBeFocused()
  await page.getByRole('button', { name: '恢复默认设置', exact: true }).click()
  await page.getByRole('button', { name: '确认恢复' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-agm-theme', 'light')
  await expect(page.getByRole('slider', { name: '面板不透明度' })).toHaveAttribute('aria-valuenow', '88')
  await page.getByRole('button', { name: '空间', exact: true }).click()
  await expect(page.locator('.world-marker')).toHaveCount(3)
})

test('sound playback survives panel changes and stops on standby', async ({ page }) => {
  await page.addInitScript(() => {
    class TestAudioContext {
      destination = {}
      currentTime = 0
      createGain() {
        return { gain: { value: 0, setTargetAtTime() {} }, connect() {}, disconnect() {} }
      }

      createOscillator() {
        return { frequency: { value: 0 }, detune: { value: 0 }, connect() {}, start() {}, stop() {}, disconnect() {} }
      }

      async resume() {}
      async suspend() {}
      async close() {}
    }
    Object.defineProperty(window, 'AudioContext', { configurable: true, value: TestAudioContext })
  })
  await page.goto('/ar/')
  await page.getByRole('button', { name: '声音', exact: true }).click()
  await page.getByRole('button', { name: '播放声音', exact: true }).click()
  await expect(page.getByRole('button', { name: '暂停声音' })).toBeVisible()
  await page.getByRole('button', { name: '下一首' }).click()
  await expect(page.getByRole('heading', { name: '浮游时刻' })).toBeVisible()
  await page.getByRole('button', { name: '空间', exact: true }).click()
  await page.getByRole('button', { name: '声音', exact: true }).click()
  await expect(page.getByRole('button', { name: '暂停声音' })).toBeVisible()
  await openSystemApp(page, '设备')
  await page.getByRole('button', { name: '待机', exact: true }).click()
  await page.getByRole('button', { name: '声音', exact: true }).click()
  await expect(page.getByRole('button', { name: '播放声音', exact: true })).toBeDisabled()
})

test('mobile anchors, route controls and HUD recovery remain usable', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/ar/')
  await page.getByRole('button', { name: '空间', exact: true }).click()
  await page.getByRole('button', { name: '选择玻璃回廊' }).click()
  await expect(page.locator('.selected-place h3')).toContainText('玻璃回廊')
  await page.getByRole('button', { name: '导航', exact: true }).click()
  await page.getByRole('button', { name: '显示到中央绿洲的路线' }).click()
  await expect(page.getByRole('button', { name: '中央绿洲 45 m', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: '开始模拟导航' }).click()
  await page.getByRole('button', { name: '前进一步' }).click()
  await expect(page.locator('.route-stops [aria-current="step"]')).toContainText('前方步道')
  await page.getByRole('switch', { name: '显示 HUD' }).click()
  await expect(page.locator('.device-window')).toHaveCount(0)
  await page.getByRole('switch', { name: '显示 HUD' }).click()
  await expect(page.getByRole('button', { name: '前进一步' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('depth and curves are independent, persist and stop for reduced motion', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.goto('/ar/')
  const view = page.locator('.ar-app')
  await openSystemApp(page, '设置')
  await expect(page.getByRole('switch', { name: '景深动画' })).not.toBeChecked()
  await expect(page.getByRole('switch', { name: '弧线视界' })).not.toBeChecked()
  await expect(page.locator('.system-rule')).toBeVisible()
  await page.getByRole('switch', { name: '景深动画' }).click()
  await expect(view).toHaveClass(/has-depth/)
  await expect(page.locator('.system-arc')).toHaveCount(0)
  await page.mouse.move(80, 280)
  await expect.poll(() => view.evaluate(element => element.style.getPropertyValue('--depth-x'))).not.toBe('')
  await expect(page.locator('.device-window')).not.toHaveCSS('translate', 'none')
  await page.getByRole('switch', { name: '弧线视界' }).click()
  await expect(page.locator('.system-arc')).toBeVisible()
  await expect(page.locator('.dock-arc')).toBeVisible()
  const edge = page.getByRole('button', { name: '镜像画面', exact: true })
  await expect(edge).toHaveCSS('translate', '0px 12px')
  await page.reload()
  await openSystemApp(page, '设置')
  await expect(page.getByRole('switch', { name: '景深动画' })).toBeChecked()
  await expect(page.getByRole('switch', { name: '弧线视界' })).toBeChecked()
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(view).not.toHaveClass(/has-depth/)
  await expect(page.getByText('系统已开启减少动态效果，景深动画暂停；弧线外观仍可使用。')).toBeVisible()
  await expect(page.locator('.system-arc')).toBeVisible()
  await expect(page.locator('.device-window')).toHaveCSS('animation-name', 'none')
  await page.mouse.move(90, 300)
  await expect.poll(() => view.evaluate(element => element.style.getPropertyValue('--depth-x'))).toBe('')
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await expect(view).toHaveClass(/has-depth/)
  await page.getByRole('switch', { name: '景深动画' }).click()
  await expect(view).not.toHaveClass(/has-depth/)
  await expect(page.locator('.system-arc')).toBeVisible()
  await page.getByRole('button', { name: '恢复默认设置', exact: true }).click()
  await page.getByRole('button', { name: '确认恢复' }).click()
  await expect(page.getByRole('switch', { name: '弧线视界' })).not.toBeChecked()
  await expect(page.locator('.system-rule')).toBeVisible()
  await expect(edge).toHaveCSS('translate', 'none')
})

test('curved mobile HUD keeps controls reachable and hiding HUD stops depth', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.goto('/ar/')
  await openSystemApp(page, '设置')
  await page.getByRole('switch', { name: '景深动画' }).click()
  await page.getByRole('switch', { name: '弧线视界' }).click()
  await page.getByRole('button', { name: '导航', exact: true }).click()
  await page.getByRole('button', { name: '显示到中央绿洲的路线' }).click()
  await page.getByRole('button', { name: '开始模拟导航' }).click()
  await page.getByRole('button', { name: '前进一步' }).click()
  await expect(page.getByRole('progressbar', { name: '路线进度' })).toHaveAttribute('aria-valuenow', '25')
  await page.getByRole('switch', { name: '显示 HUD' }).click()
  await expect(page.locator('.ar-app')).not.toHaveClass(/has-depth/)
  await page.getByRole('switch', { name: '显示 HUD' }).click()
  await expect(page.locator('.ar-app')).toHaveClass(/has-depth/)
  const docs = await page.getByRole('link', { name: '组件文档' }).boundingBox()
  expect(docs!.x + docs!.width).toBeLessThanOrEqual(390)
  expect(docs!.y + docs!.height).toBeLessThanOrEqual(844)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth && document.documentElement.scrollHeight <= innerHeight)).toBe(true)
})
