// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AgmMap: typeof import('./components/app/AgmMap.vue')['default']
    AgmWeather: typeof import('./components/app/AgmWeather.vue')['default']
    AgmWindow: typeof import('./components/ui/AgmWindow.vue')['default']
    AudioBtn: typeof import('./components/menu/AudioBtn.vue')['default']
    AugmaUi: typeof import('./components/AugmaUi.vue')['default']
    BottomMenu: typeof import('./components/ui/BottomMenu.vue')['default']
    FaceApi: typeof import('./components/examples/FaceApi.vue')['default']
    FullscreenBtn: typeof import('./components/menu/FullscreenBtn.vue')['default']
    MenuBtn: typeof import('./components/menu/MenuBtn.vue')['default']
    SystemBar: typeof import('./components/ui/SystemBar.vue')['default']
    TfjsYolo: typeof import('./components/examples/TfjsYolo.vue')['default']
    WebCam: typeof import('./components/WebCam.vue')['default']
  }
}

export { }
