// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AgmBottomMenu: typeof import('augma')['AgmBottomMenu']
    AgmButton: typeof import('augma')['AgmButton']
    AgmCard: typeof import('augma')['AgmCard']
    AgmClock: typeof import('augma')['AgmClock']
    AgmDialog: typeof import('augma')['AgmDialog']
    AgmIcon: typeof import('augma')['AgmIcon']
    AgmMap: typeof import('./components/app/AgmMap.vue')['default']
    AgmMenu: typeof import('augma')['AgmMenu']
    AgmWeather: typeof import('./components/app/AgmWeather.vue')['default']
    AgmWindow: typeof import('./components/ui/AgmWindow.vue')['default']
    AudioBtn: typeof import('./components/menu/AudioBtn.vue')['default']
    AugmaUi: typeof import('./components/AugmaUi.vue')['default']
    BottomMenu: typeof import('./components/ui/BottomMenu.vue')['default']
    FaceApi: typeof import('./components/examples/FaceApi.vue')['default']
    FullscreenBtn: typeof import('./components/menu/FullscreenBtn.vue')['default']
    IMdiAlert: typeof import('~icons/mdi/alert')['default']
    IMdiDotsHorizontal: typeof import('~icons/mdi/dots-horizontal')['default']
    IMdiDotsVertical: typeof import('~icons/mdi/dots-vertical')['default']
    IMdiFullscreen: typeof import('~icons/mdi/fullscreen')['default']
    IMdiFullscreenExit: typeof import('~icons/mdi/fullscreen-exit')['default']
    IMdiMicrophone: typeof import('~icons/mdi/microphone')['default']
    IMdiMicrophoneSettings: typeof import('~icons/mdi/microphone-settings')['default']
    IMdiWeatherPartlyCloudy: typeof import('~icons/mdi/weather-partly-cloudy')['default']
    MenuBtn: typeof import('./components/menu/MenuBtn.vue')['default']
    SystemBar: typeof import('./components/ui/SystemBar.vue')['default']
    TfjsYolo: typeof import('./components/examples/TfjsYolo.vue')['default']
    WebCam: typeof import('./components/WebCam.vue')['default']
  }
}

export { }
