import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises'
import { relative, resolve } from 'node:path'
import { compileScript, parse } from '@vue/compiler-sfc'
import { components, origin, version } from './catalog.mjs'
import { extractProps } from './component-contract.mjs'

for (const path of ['package.json', 'packages/core/package.json', 'packages/augma/package.json']) {
  const pkg = JSON.parse(await readFile(path, 'utf8'))
  if (pkg.version !== version)
    throw new Error(`${path} must match component contract v${version}`)
}
const site = resolve('apps/site')
const publicDir = resolve(site, 'public')
for (const dir of ['r', 'markdown']) {
  await rm(resolve(publicDir, dir), { recursive: true, force: true })
  await mkdir(resolve(publicDir, dir), { recursive: true })
}
await mkdir(resolve(site, 'components'), { recursive: true })
const index = []
for (const item of components) {
  const source = await readFile(
    `packages/augma/src/components/${item.name}.vue`,
    'utf8',
  )
  const { descriptor } = parse(source)
  const compiled = compileScript(descriptor, { id: item.slug })
  const declarations = extractProps(descriptor, compiled)
  if (declarations.size !== item.props.length) {
    throw new Error(
      `${item.name}: describe every public property in the catalog`,
    )
  }
  item.props = item.props.map((prop) => {
    const declaration = declarations.get(prop.name)
    if (!declaration)
      throw new Error(`${item.name}: undocumented or unknown prop ${prop.name}`)
    return { ...declaration, description: prop.description }
  })
  const api = item.props
    .map(
      p =>
        `| \`${p.name}\` | ${p.type.replaceAll('|', '\\|')} | ${p.default} | ${p.description} |`,
    )
    .join('\n')
  const doc = `<!-- Generated by scripts/generate.mjs from the public catalog. -->\n# ${item.title}\n\n${item.description}\n\n## 基础用法\n\n<DemoPreview name="${item.slug}" />\n\n## API\n\n| 属性 | 类型 | 默认值 | 说明 |\n| --- | --- | --- | --- |\n${api}\n\n${item.events ? `### 事件\n\n${item.events.map(e => `- \`${e}\``).join('\n')}\n\n` : ''}${item.slots ? `### 插槽\n\n${item.slots.map(s => `- ${s}`).join('\n')}\n\n` : ''}## 键盘操作与使用边界\n\n${item.keyboard}\n\n## 安装\n\n\`\`\`ts\nimport { ${item.name} } from 'augma'\nimport 'augma/style.css'\n\`\`\`\n${item.registry ? `\n复制可编辑源码：\n\n\`\`\`sh\npnpm dlx shadcn-vue@2.8.2 add ${origin}/r/${item.slug}.json\n\`\`\`\n` : ''}`
  await writeFile(resolve(site, `components/${item.slug}.md`), doc)
  const entry = {
    ...item,
    version,
    import: `import { ${item.name} } from 'augma'`,
    url: `${origin}/components/${item.slug}`,
    example: `${origin}/markdown/examples/${item.slug}.vue`,
    registry: item.registry ? `${origin}/r/${item.slug}.json` : undefined,
  }
  index.push(entry)
  if (item.registry) {
    const deps = [`@augma/core@${version}`]
    if (source.includes('from \'reka-ui\''))
      deps.push('reka-ui@2.10.5')
    await writeFile(
      resolve(publicDir, `r/${item.slug}.json`),
      `${JSON.stringify({ $schema: 'https://shadcn-vue.com/schema/registry-item.json', name: item.slug, type: 'registry:ui', title: item.title, description: item.description, dependencies: deps, files: [{ path: `ui/augma/${item.name}.vue`, type: 'registry:ui', content: source }], docs: 'Import \'@augma/core/style.css\' once in your application entry. Vue 3.5+ is required. This source is yours to edit.' }, null, 2)}\n`,
    )
  }
}
await writeFile(
  resolve(publicDir, 'components.json'),
  `${JSON.stringify({ schemaVersion: 1, version, origin, components: index }, null, 2)}\n`,
)
await writeFile(
  resolve(publicDir, 'r/index.json'),
  `${JSON.stringify({ name: 'augma', homepage: origin, items: index.filter(c => c.registry).map(c => ({ name: c.slug, type: 'registry:ui', title: c.title, url: c.registry })) }, null, 2)}\n`,
)
await mkdir(resolve(publicDir, 'markdown/examples'), { recursive: true })
for (const item of components) {
  await writeFile(
    resolve(publicDir, `markdown/examples/${item.slug}.vue`),
    await readFile(`examples/components/${item.slug}.vue`),
  )
}
await mkdir(resolve(publicDir, 'markdown/compositions'), { recursive: true })
for (const file of await readdir('examples/compositions')) {
  if (file.endsWith('.vue')) {
    await writeFile(
      resolve(publicDir, 'markdown/compositions', file),
      await readFile(`examples/compositions/${file}`),
    )
  }
}
const documents = []
async function collect(dir) {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    if (
      entry.name.startsWith('.')
      || entry.name === 'public'
      || entry.name === 'node_modules'
    ) {
      continue
    }
    const path = resolve(dir, entry.name)
    if (entry.isDirectory()) {
      await collect(path)
    }
    else if (entry.name.endsWith('.md')) {
      const rel = relative(site, path)
      let content = (await readFile(path, 'utf8'))
        .replace(/^---\n[\s\S]*?\n---\n/, '')
        .replace(/<!--.*?-->/gs, '')
      content = content.replace(
        /<DemoPreview name="([\w-]+)"\s*\/>/g,
        (_, slug) => `[Vue example](${origin}/markdown/examples/${slug}.vue)`,
      )
      content = content.replace(
        /<(HomePage|ShowcasePage|ComponentCatalog)\s*\/>/g,
        '',
      )
      const dest = resolve(publicDir, 'markdown', rel)
      await mkdir(resolve(dest, '..'), { recursive: true })
      await writeFile(dest, content)
      documents.push({ rel, content })
    }
  }
}
await collect(site)
await writeFile(
  resolve(publicDir, 'llms.txt'),
  `# Augma\n\n> AR-inspired design tokens and Vue 3 components. Version ${version}.\n\n- [Getting started](${origin}/markdown/guide/index.md)\n- [Design system](${origin}/markdown/design/index.md)\n- [AI integration](${origin}/markdown/ai/index.md)\n- [Component contract](${origin}/components.json)\n- [Complete documentation](${origin}/llms-full.txt)\n- [Agent Skill](https://github.com/YunYouJun/augma/blob/main/skills/augma/SKILL.md)\n\n## Components\n${index.map(c => `- [${c.name}](${origin}/markdown/components/${c.slug}.md): ${c.description}`).join('\n')}\n`,
)
await writeFile(
  resolve(publicDir, 'llms-full.txt'),
  `# Augma ${version}\n\n${documents.map(d => `Source: ${origin}/markdown/${d.rel}\n\n${d.content}`).join('\n\n---\n\n')}`,
)
console.log(
  `Generated ${index.length} component contracts, ${index.filter(c => c.registry).length} Registry entries and ${documents.length} Markdown documents.`,
)
